chore(src): adjust examples to work with Camunda Cloud
zeebe-io/zeebe-get-started-go-client pull request #6
Opened 2020-12-21 15:34 UTC by pihme

Changes related to https://github.com/camunda-cloud/camunda-cloud-documentation/issues/89

Change set:
- Adjusts Readme to explain variant with Camunda Cloud and with local deployment
- Adjusts the examples to work with either a Camunda Cloud cluster or with a local deployment

2020-12-21 15:35 UTC, pihme commented
Merge should wait until new documentation is released. Otherwise, some links are not yet available.

2021-01-06 15:46 UTC, MiguelPires requested changes
Just a few small issues with formatting and the new code. I added suggestions to make it easier to change but feel free to do something different if you want. 
Also, I noticed this example has the readyClose channel used by the worker to signal that it can be closed. This was added to the old Zeebe docs to fix a deadlock in the code but I got some feedback from two users who thought it was confusing. I opened an issue for it https://github.com/zeebe-io/zeebe/issues/5444 this is out of scope for this PR but I just thought I'd bring it up since you're touching these files

2021-01-06 15:46 UTC, MiguelPires commented on src/example-1.go
> +
The formatting is off and there shouldn't be parentheses around the condition in the `if. I think this should fix it
```suggestion
    gatewayAddr := os.Getenv("ZEEBE_ADDRESS")
    var plainText bool

    if gatewayAddr == "" {
        gatewayAddr = ZeebeAddr
        plainText = true
    }
```

2021-01-06 15:46 UTC, MiguelPires commented on src/example-2.go
> +  }
The formatting is off and there shouldn't be parentheses around the condition in the `if`.
```suggestion
    gatewayAddr := os.Getenv("ZEEBE_ADDRESS")
    var plainText bool

    if gatewayAddr == "" {
        gatewayAddr = ZeebeAddr
        plainText = true
    }
```

2021-01-06 15:46 UTC, MiguelPires commented on src/example-3.go
> +  }
Same
```suggestion
    gatewayAddr := os.Getenv("ZEEBE_ADDRESS")
    var plainText bool

    if gatewayAddr == "" {
        gatewayAddr = ZeebeAddr
        plainText = true
    }
```

2021-01-06 15:46 UTC, MiguelPires commented on src/example-4.go
> +  }
Same
```suggestion
    gatewayAddr := os.Getenv("ZEEBE_ADDRESS")
    var plainText bool

    if gatewayAddr == "" {
        gatewayAddr = ZeebeAddr
        plainText = true
    }
```

2021-01-06 15:46 UTC, MiguelPires commented on src/example-1.go
> +to download a file with above lines filled out for you.
```suggestion
to download a file with the lines above filled out for you.
```
Or something else, but "with above lines" sounds weird to me.

2021-01-06 15:46 UTC, MiguelPires commented on src/example-2.go
> +to download a file with above lines filled out for you.
```suggestion
to download a file with the lines above filled out for you.
```

2021-01-06 15:46 UTC, MiguelPires commented on src/example-3.go
> +to download a file with above lines filled out for you.
```suggestion
to download a file with the lines above filled out for you.
```

2021-01-06 15:46 UTC, MiguelPires commented on src/example-4.go
> +to download a file with above lines filled out for you.
```suggestion
to download a file with the lines above filled out for you.
```

2021-01-07 12:29 UTC, pihme commented
@MiguelPires Since indentation seems to be important I added an https://editorconfig.org/ file. Not 100% sure on the settings though. Please have a look whether the settings are compliant with Go style.

2021-01-07 13:07 UTC, MiguelPires commented
You can just use `gofmt` to format the code according to the language's standards. I should've done that instead of eyeballing it in the Github suggestions, my bad. Also, did you run the examples?

2021-01-07 13:09 UTC, pihme commented
I did run the examples with a local server

2021-01-07 13:09 UTC, pihme commented
Should we remove `.editorconfig` then if there is a dedicated tool in the Go ecosystem?

2021-01-07 13:11 UTC, MiguelPires commented
> Should we remove `.editorconfig` then if there is a dedicated tool in the Go ecosystem?

Sure, you can do that and also squash so it's ready to merge

2021-01-07 13:22 UTC, MiguelPires approved these changes
bors r+

2021-01-07 13:24 UTC, merged